### ISSUE TITLE
move server init to earlier in lifecycle

### ISSUE THREAD

**Issue by softwareCobbler** [softwareCobbler/luceedebug#13]
Right now the dap server and jdwp connections are initialized in response to Lucee loading `PageContextImpl`. This require users to "prime" the engine, by making a typical http request to it first. Investigate moving networking init to earlier in the lifecycle, optimally during agent premain.

**Comment by jamiejackson** [comment]
Documented the need for "priming" in the latest commit of this PR. It was one of the things that had been blocking me, previously.

#11

**Comment by softwareCobbler** [comment]
This should be improved with 476c7f6722caade604f9f15d969484d56b0ffc87 -- all the server stuff should (!) spawn prior to the first HTTP request into the engine.

**Comment by jamiejackson** [comment]
Nice! I just tried it and the debugger was able to connect before any requests were made.

Observation: Before I exercise the code, the breakpoints show up as "Unverified Breakpoint." Once the code is exercised, the breakpoint stops appropriately and the breakpoints light up.

It makes sense why it works that way since it can't associate breakpoints until class files are compiled.

**Comment by jamiejackson** [comment]
I created a PR to remove "priming" from the readme.

Is there more that you wanted to do before closing this ticket, by the way?

**Comment by softwareCobbler** [comment]
No not much else to do here.
