### ISSUE TITLE
VS Code extension not showing up?

### ISSUE THREAD

**Issue by zspitzer** [softwareCobbler/luceedebug#58]
The debugger ext has disappeared from both the add configurations menu and the command palette?

I tried uninstalling and reinstalling, didn't help, it was all working wonderfully last week?

Nothing show up under the toggle developer tools?

PS: the category for the VSCode extension is currently `Other`, the install debuggers menu shortcut searches for `@category:debuggers` 
<img width="360" alt="image" src="https://github.com/user-attachments/assets/0668c884-8205-43e8-b041-30ca6d398e97">

The agent is being loaded successfully

Listening for transport dt_socket at address: 9999
[luceedebug] version 2.0.12
[luceedebug] agent premain complete

VS Code Version: 1.92.1
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by softwareCobbler** [comment]
I'm not sure what the problem being reported here is. `launch.json` no longer has a cfml debug config in it? I'm also on vscode 1.92.1 and haven't experienced anything out of the ordinary.

Tagging the extension with "debugger" does seem like a good idea, I didn't realize that was a thing.

**Comment by jamiejackson** [comment]
More detail in (dupe) #60.

**Comment by softwareCobbler** [comment]
Fixed in extension 2.0.10:

Difference between "initialConfiguration" and "configurationSnippets", where initialConfiguration provides an "initial default" for particular file types (I think if a file of that type is open when the default is requested), and configurationSnippets provides those auto-completable snippets. So now there are both.

"debug class and breakpoint info" not appearing if not connected to the server. Now it will always appear, even if not connected to the server; but if not connected to the server, attempting to run it will error with a message to the effect of "sorry, the debugger is not connected to Lucee".

Added "debuggers" category tag to extension.

**Comment by zspitzer** [comment]
great work, it's all working again!
