### ISSUE TITLE
how to debug the luceedebug.jar

### ISSUE THREAD

**Issue by pibica** [softwareCobbler/luceedebug#64]
Is it a way to debug in the 'java world' a Lucee / tomcat process that has luceedebug.jar running.
As luceejdebug.jar is connected to the jpda port, I'm not able to attach another java debugger.
My goal is to understand what happens in the luceebug.jar code when I've an issue with the lucee debugger.

**Comment by softwareCobbler** [comment]
Unfortunately the approach we've taken does not support "debugging the debugger", because we connect to the single libjdwp connector and hold onto it for the life if the JVM. Hence no other clients can connect to libjdwp. This is the same reason it is not possible to run luceedebug and FusionReactor at the same time.

So, a lot of strategic `System.out.println` or similar logging.
